#pragma once
#ifndef MT_ENUM_H
#define MT_ENUM_H
#include <stdint.h>
#include <stdlib.h>
enum csv_column_t {
  CSV_COLUMN_YEAR_MONTH_DAY,
  CSV_COLUMN_HOUR_MINUTE,
  CSV_COLUMN_OPEN,
  CSV_COLUMN_HIGH,
  CSV_COLUMN_LOW,
  CSV_COLUMN_CLOSE,
  CSV_COLUMN_VOLUME,
  CSV_COLUMNS_QTY,
};
static const size_t MARKET_PERIOD_LENGTH_HOURS = 4;
enum ema_moving_average_type_t {
  EMA_MOVING_AVERAGE_TYPE_EXPONENTIAL_AVERAGE,
};
enum ema_timeframe_type_t {
  EMA_TIMEFRAME_TYPE_CURRENT,
};
enum ema_shift_type_t {
  EMA_SHIFT_TYPE_CURRENT,
};
enum ema_applied_price_type_t {
  EMA_APPLIED_PRICE_TYPE_CLOSE,
};
enum ema_period_duration_type_t {
  MARKET_PERIOD_DURATION_TYPE_LAST_EIGHT_HOURS = 0,
  MARKET_PERIOD_DURATION_TYPE_LAST_TWELVE_HOURS,
  MARKET_PERIOD_DURATION_TYPE_LAST_DAY,
  MARKET_PERIOD_DURATION_TYPE_LAST_TWO_DAYS,
  MARKET_PERIOD_DURATION_TYPE_LAST_WEEK,
  MARKET_PERIOD_DURATION_TYPE_LAST_MONTH,
  MARKET_PERIOD_DURATION_TYPE_LAST_THREE_MONTHS,
  MARKET_PERIOD_DURATION_TYPE_LAST_SIX_MONTHS,
  MARKET_PERIOD_DURATION_TYPE_LAST_YEAR,
  MARKET_PERIOD_DURATION_TYPES_QTY,
};
#endif
