name: abc
keys:
  - name: Activate Alacritty
    key: alt+shift+5
    action: alacritty
    action_type: ActivateApplication
    enabled: yes
  - name: Dectivate Alacritty
    key: alt+shift+6
    action: alacritty
    action_type: DeactivateApplication
    enabled: yes
  - name: Activate Kitty
    key: alt+shift+7
    action: kitty
    action_type: ActivateApplication
    enabled: yes
  - name: Activate Kitty
    key: alt+shift+0
    action: kitty
    action_type: ActivateApplication
    enabled: yes
  - name: Activate Richard
    key: alt+shift+9
    action: richard
    action_type: ActivateApplication
    enabled: yes
