#pragma once
#ifndef ICONS_H
#define ICONS_H
//////////////////////////////////////
#include <assert.h>
#include <ctype.h>
#include <errno.h>
#include <inttypes.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
//////////////////////////////////////
#define MAX_ICON_CATEGORIES    32
enum icon_file_type_t {
  ICON_FILE_TYPE_ICNS,
  ICON_FILE_TYPE_PNG,
  ICON_FILE_TYPES_QTY,
};
struct icon_png_file_t {
  const char                  *path, *hash;
  const size_t                size;
  const int                   width, height;
  const unsigned char         *data;
  const int                   bits;
  const enum icon_file_type_t type;
};
struct icon_file_t {
  const char                  *path, *hash;
  const size_t                size;
  const unsigned char         *data;
  const enum icon_file_type_t type;
};
struct icon_files_t {
  struct icon_file_t     icn;
  struct icon_png_file_t *pngs;
};
struct icon_t {
  const char          *name, *categories[MAX_ICON_CATEGORIES];
  struct icon_files_t files;
};
static const char *icon_names[] = { "1password",
                                    "activitymonitor",
                                    "adobe",
                                    "airport",
                                    "alacritty",
                                    "ali",
                                    "android_file_transfer",
                                    "android_studio",
                                    "anti_virus",
                                    "app",
                                    "app_cleaner",
                                    "app_empty",
                                    "app_store",
                                    "appcleaner",
                                    "appdealwhale",
                                    "appicns_jw_canary",
                                    "appicns_jw_chrome_bold",
                                    "appicns_jw_chromium",
                                    "appicns_jw_gitbox",
                                    "appicns_jw_mamp",
                                    "appicns_jw_reminders",
                                    "appicns_jw_sublimetext",
                                    "appicns_jw_toggl",
                                    "appicns_lg_dropbox",
                                    "appicns_rs_1password",
                                    "appicns_rs_codekit",
                                    "appicns_rs_eclipse",
                                    "appicns_rs_notationalvelocity",
                                    "appicns_rs_xcode",
                                    "appiconnew",
                                    "applescript",
                                    "appstore",
                                    "astro",
                                    "atom",
                                    "automator",
                                    "axure",
                                    "bartender",
                                    "basex",
                                    "batterydiag",
                                    "better_snap_tool",
                                    "betterrename",
                                    "bettersnaptool",
                                    "black",
                                    "blackmagicdiskspeedtest",
                                    "blender",
                                    "blue_version",
                                    "bluetooth",
                                    "bootcamp",
                                    "boxy_icon",
                                    "brackets",
                                    "browser",
                                    "burn",
                                    "calculator",
                                    "calendar",
                                    "cdrviewer",
                                    "chess",
                                    "chocolate",
                                    "chrome",
                                    "cian",
                                    "cleanmydrive",
                                    "clear",
                                    "clipmenu",
                                    "coda",
                                    "code",
                                    "colorsync",
                                    "comburet",
                                    "commandc",
                                    "compiler",
                                    "console",
                                    "contacts",
                                    "countdown",
                                    "current",
                                    "cyberduck",
                                    "dark",
                                    "dark2",
                                    "dash",
                                    "degrees",
                                    "dev_folder",
                                    "dictionary",
                                    "digitalcolor",
                                    "diskdiag",
                                    "diskutility",
                                    "dockpreview",
                                    "dropbox",
                                    "dsstoreremover",
                                    "dvd_player",
                                    "dxoperspective",
                                    "eclipse",
                                    "everfont",
                                    "evernote",
                                    "evernote_yosemite_icon_by_cam",
                                    "facebook",
                                    "facetime",
                                    "facetime2",
                                    "facetime3",
                                    "facetimes",
                                    "fastpreview",
                                    "fav",
                                    "feedly",
                                    "filelistexport",
                                    "files",
                                    "filezilla",
                                    "finder",
                                    "finder2",
                                    "finder3",
                                    "finder4",
                                    "finder_red",
                                    "firefox1",
                                    "firefox2",
                                    "firefox3",
                                    "firefox4",
                                    "firefox5",
                                    "flatout2",
                                    "font_book",
                                    "fontbook",
                                    "fontbook2",
                                    "forklift",
                                    "fotor",
                                    "frankdeloupe",
                                    "getpocket",
                                    "github",
                                    "gold",
                                    "google_drive",
                                    "googlechrome",
                                    "grab",
                                    "grapher",
                                    "handbrake",
                                    "happy",
                                    "home",
                                    "iawriter",
                                    "ibooks",
                                    "icon",
                                    "icon_for_sublime_text",
                                    "icon_slate",
                                    "icon_tester",
                                    "iconverticons",
                                    "imagecapture",
                                    "imovie",
                                    "instacast",
                                    "iphoto",
                                    "istatmini",
                                    "iterm",
                                    "iterm2",
                                    "itunes",
                                    "ivi",
                                    "iviiconac",
                                    "ivory",
                                    "iwork_keynote",
                                    "iwork_numbers",
                                    "iwork_pages",
                                    "jdownloader",
                                    "keychain",
                                    "keynote",
                                    "kingdomrush",
                                    "kitty",
                                    "kitty1",
                                    "kitty_dark",
                                    "kitty_light",
                                    "launcher",
                                    "launchpad",
                                    "libreoffice",
                                    "light",
                                    "light2",
                                    "ligth",
                                    "liteicon",
                                    "lockmenow",
                                    "locko",
                                    "mactracker",
                                    "mail",
                                    "mail_icloud",
                                    "mailicon",
                                    "maps",
                                    "mediahuman",
                                    "meshlab",
                                    "messages",
                                    "meta",
                                    "metamovie",
                                    "microsoft_excel",
                                    "microsoft_onenote",
                                    "microsoft_outlook",
                                    "microsoft_powerpoint",
                                    "microsoft_word",
                                    "monthlycal",
                                    "ms_excel",
                                    "ms_outlook",
                                    "ms_powerpoint",
                                    "ms_word",
                                    "music",
                                    "mysql",
                                    "notality",
                                    "notes",
                                    "omifocus_2",
                                    "omnifocus",
                                    "onmifocus",
                                    "orange",
                                    "pages",
                                    "photobooth",
                                    "photos",
                                    "photoshop",
                                    "photoshop_cs6_icon",
                                    "pixelmator",
                                    "pixlr",
                                    "pocket",
                                    "pocket_casts",
                                    "pomodoro",
                                    "popclip",
                                    "preview",
                                    "preview2",
                                    "preview3",
                                    "primary",
                                    "processing",
                                    "prosvscons",
                                    "ps_appicon",
                                    "qq",
                                    "quicktime",
                                    "quicktimex",
                                    "razersynapse",
                                    "rdio",
                                    "readkit",
                                    "red",
                                    "reminders",
                                    "resizeit",
                                    "retinacapture",
                                    "rich",
                                    "richard",
                                    "richard1",
                                    "richard2",
                                    "ringer",
                                    "safari",
                                    "shadowsocksx",
                                    "sip",
                                    "sketch",
                                    "skitch",
                                    "skype",
                                    "slack",
                                    "soundcloud",
                                    "sourcetree",
                                    "sparkle",
                                    "spotify",
                                    "steam",
                                    "stickies",
                                    "sublime",
                                    "sublime_text_2",
                                    "sublime_text_icon",
                                    "sublimetext",
                                    "sublimt",
                                    "telegram",
                                    "terminal",
                                    "terminal2",
                                    "textedit",
                                    "texteditor",
                                    "twitter",
                                    "unarchiver",
                                    "voiceover",
                                    "wayfarer",
                                    "wechat",
                                    "whatsapp",
                                    "white",
                                    "whosonmywifi",
                                    "wunderlist",
                                    "x11",
                                    "xampp",
                                    "yellow", };
#endif
