#include <stdbool.h>
#define DEFAULT_TEXT_RESPONSE              "404 Not Found"
#define DEFAULT_RESIZE_FACTOR              400
#define UNHANDLED_REQUEST_RESPONSE_CODE    500
#define HANDLED_REQUEST_RESPONSE_CODE      200
#define DARWIN_LS_HTTPSERVER_PORT          49225
#define DARWIN_LS_HTTPSERVER_HOST          "127.0.0.1"
#define DARWIN_LS_HTTPSERVER_PROTOCOL      "http"
#undef HTTP_MAX_TOTAL_EST_MEM_USAGE
#undef HTTP_MAX_REQUEST_BUF_SIZE
#undef HTTP_REQUEST_TIMEOUT
#define HTTP_MAX_TOTAL_EST_MEM_USAGE    1024 * 1024 * 64
#define HTTP_MAX_REQUEST_BUF_SIZE       1024 * 1024
#define HTTP_REQUEST_TIMEOUT            3
