#pragma once
#ifndef GPP_DLS_OPTIONS_H
#define GPP_DLS_OPTIONS_H

enum dls_option_id_t {
  DLS_OPTION_ID_DEBUG_MODE,
  DLS_OPTION_ID_VERBOSE_MODE,
  DLS_OPTION_ID_FONT_NAME,
  DLS_OPTION_ID_SPACE_ID,
  DLS_OPTION_ID_IDS,
  DLS_OPTION_ID_WINDOW_ID,
  DLS_OPTION_IDS_QTY,
};

#endif
